### ISSUE TITLE
plan for splitting the package

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphNeuralNetworks.jl#450]
The codebase is currently undergoing a factorization whose final outcome is to have several packages hosted in the same monorepo (for developing convenience, see #433):
- `GNNGraphs.jl`: graph types and graph operations. Depends on `Graphs.jl` and on `NNlib.jl`. 
- `GNNlib.jl`: functional implementation of graph convolutional layers. Depends on `GNNGraphs.jl`.
- `GraphNeuralNetworks.jl` or `FluxGNN.jl`: Stateful graph convolutional layers based on `Flux.jl`. This will be the fronted package for Flux users. Depends on `GNNlib.jl`, `GNNGraphs.jl`, and `Flux.jl`.
- `LuxGNN.jl`: Stateless graph convolutional layers satisfying Lux's interface. Depends on `GNNlib.jl`, `GNNGraphs.jl`, and `Lux.jl`.

This way we will introduce Lux support (#372) and the Flux and Lux frontends will be only tiny wrappers around a shared codebase given by GNNlib.jl and GNNGraphs.jl. 

I will keep track here of the transition status:
- [x] Create and register the package `GNNlib.jl`. `GraphNeuralNetworks.jl` will not depend on it yet. #432 
- [x] Create and register the package `GNNGraphs.jl`. #446, https://github.com/JuliaRegistries/General/pull/111443
- [x] Setup multi-package CI (#451)
- [x] Make `GraphNeuralNetworks.jl` depend on `GNNGraphs.jl`  #453 
    - [x] Make sure to include all the latest changes to the GNNGraphs module into the GNNGraphs package
- [x] Make `GNNlib.jl` depend on `GNNGraphs.jl`
- [x] Create `GNNLux.jl` depending on `GNNlib.jl` and `GNNGraphs.jl`. #460  
- [x] Make `GraphNeuralNetworks.jl` depend on `NNlib.jl`. #464 
- [x] Setup multi-package documentation (#456)
    - [ ] write developer docs
